### ISSUE TITLE
Separation of interface and implementation

### ISSUE THREAD

**Issue by gasche** [bobbypriambodo/ocaml-documentation-guideline#2]
You write:

> This item recommends putting documentation in .mli files. You can put documentation in .ml files, but as OCaml is a strict language where order of declarations are important, you will have less flexibility in organizing your doc comments. .mli files do not have that restriction.

I don't think that "flexibility in the order of entries" is the main argument there: the point is that OCaml encourages people to separate the *implementation* of a module from its *interface*, and that the documentation goes in the interface, unburdened from implementation details. (In particular, it is common for libraries to have both implementation comments and documentation comments, and these are separate things.)

**Comment by bobbypriam** [comment]
Noted, I'll try to improve it later. As always, for anyone reading this, PR is welcome while open!

**Comment by bobbypriam** [comment]
Should be addressed by the linked commit. Thanks for the feedback!
