### ISSUE TITLE
In signatures put document comments after the structure elements & document all signature items

### ISSUE THREAD

**Issue by dbuenzli** [bobbypriambodo/ocaml-documentation-guideline#4]
(except for modules). There are a few advantages to this.

1. When you scan `mli`s your eyes anchor on `type`, `val`, etc. keywords. Once you spotted the one of interest the documentation then follows, in the scanning direction, rather than having to switch directions.

2. That's the way they end up being presented by documentation generators (`ocamldoc`, `odoc`) so there's less cognitive dissonance when you switch from one to the other. An documenation generator output is just a prettified view of your `.mli`.

**Comment by bobbypriam** [comment]
That is a nice recommendation and reasonable arguments. However, it seems to me at least in the [Jane Street styleguide](https://opensource.janestreet.com/standards/) they don't enforce this (or they just don't have a particular view about it). I'm also interested in hearing whether they have a consideration for it.

That said, perhaps being authoritative about it (with good reasons) in the document would indeed work better.

**Comment by dbuenzli** [comment]
Well historically Jane Street hasn't been a top notch example of documentation producer so I wouldn't cling too much to whatever they may be saying. And for example from the document you linked this:

```
If you really can’t find anything useful to add with a comment, it’s acceptable to have 
a comment that is redundant with the type and name, particularly in broadly-aimed 
libraries like Base and Core. This reflects the fact that it’s considered gauche in 
some circles to have functions with no documentation whatsoever. Bytes module, 
we might have this

(** [length t] returns the number of bytes in [t]. *)
val length : t -> int
even though the content is largely duplicative.
```

entirely misses the mark in my opinion. Broccoli documentation strings are useful, especially if you follow (which you should) the pattern of describing the *values* resulting from applications (`[f x y z] is ...`, note not `returns`): they provide a natural language denotation of your values, that is how you should *read* the code. Funnily in the particular example they give, there is still some information/confirmation in the doc string: the units of the returned magnitude.

**Comment by bobbypriam** [comment]
Well noted, and yeah I think I will go ahead and incorporate this recommendation in the "Document all your signatures" item. Thanks!

> Brocoli documentation strings

I have just heard of this term, do you know where I could read more about this? I mentioned about that way of writing documentation later in the document but I didn't know it was something standardized.

**Comment by dbuenzli** [comment]
> Well noted, and yeah I think I will go ahead and incorporate this recommendation in the "Document all your signatures" item

Beyond the natural-language denotational semantics argument for code reading given above you can also add:

1. You don't have to spend time to ask yourself whether a signature item warrants a documentation string or not. Just do it, even if it feels entirely pointless and redundant it has to become a reflex.
2. You might find the semantics of a signature item obvious based solely on its name, but that's just because *you* implemented it. A reader not familliar with the implementation may not find it obvious.

> I have just heard of this term, do you know where I could read more about this?

Oh that's just a reference to J.-Y. Girard making fun of Tarskian semantics see for example section 5.1 in [this document](http://girard.perso.math.cnrs.fr/truth.pdf).

**Comment by stevebleazard** [comment]
@dbuenzli - can you give a few examples of where comments would go for types and functions? I think I am following but want to be sure. Also, what are Broccoli documentation strings?

**Comment by jnavila** [comment]
Putting the doc string after the type declaration does not seem to work properly for variants. The doc string is not processed correctly and is just inlined as is after the declaration.

**Comment by dbuenzli** [comment]
> @dbuenzli - can you give a few examples of where comments would go for types and functions?

Right after your definitions. I have thousands of lines of documented mli interfaces just have a look at my packages if you need more examples.

> Also, what are Broccoli documentation strings?

Just explained that in my previous comment. 

> Putting the doc string after the type declaration does not seem to work properly for variants.

It does. You just need to add a `(** *)` comment on your last case if you don't document it. Otherwise your type comment will be attached to the last case.
